version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/AWS-Containerization/lab1-ecr-docker-pipeline"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/AWS-Containerization/lab1-ecr-docker-pipeline/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
