template-file-path: AWS-Containerization/lab1-ecr-docker-pipeline/infra/ecr-stack.yaml
parameters:
  CIRoleArn: arn:aws:iam::697863031884:role/ecr-github-lab-role
  RepositoryName: ecr-github-app
tags: {}
